### PR TITLE
feat: added UpdatableOperatorFiltererUpgradeable contract & tests

### PR DESCRIPTION
**Pull request by balajmarius**
An abstract contract whose init function automatically registers and optionally subscribes to or copies another registrant's entries in the `OperatorFilterRegistry`. This contract allows the `Owner` to update the  `OperatorFilterRegistry` address via `updateOperatorFilterRegistryAddress`, including to the zero address,  which will bypass registry checks.

Note that OpenSea will still disable creator fee enforcement if filtered operators begin fulfilling orders on-chain, eg, if the registry is revoked or bypassed.

This smart contract is meant to be inherited by token contracts so they can use the following:
 - `onlyAllowedOperator` modifier for `transferFrom` and `safeTransferFrom` methods.
 - `onlyAllowedOperatorApproval` modifier for `approve` and `setApprovalForAll` methods.

Also, use `updateOperatorFilterRegistryAddress` function to change the registry address if needed.

image

### CODE REVIEW

**Comment by shoenseiwaso** [comment]
OpenSea team, can we get this merged and released soon?

**Comment by n0thingness** [comment]
@operatorfilterer What's the timeline on this feature?

**Comment by operatorfilterer** [comment]
Thanks for the PR! The underlying contracts and patterns have changed a bit since it was opened. Can you update to follow the newer patterns in the main branch? Namely upgradeable storage layouts, constants, internal `_checkFilterOperator` function calls. Then we can get that merged in. Thanks!

**Comment by navopw** [comment]
I would really appreciate this change!

**Comment by abarbatei** [comment]
@operatorfilterer thanks for the update! will add the indicated changes asap

**Comment by abarbatei** [comment]
@operatorfilterer could you take a look?

**Comment by n0thingness** [comment]
@operatorfilterer We're blocked by this so we'd greatly appreciate it if we could get this in

**Comment by danbridge** [comment]
Hello @operatorfilterer  do you have an ETA on the above approval? We're assessing whether to fork at this point or see if we can wait, thanks

**Comment by shoenseiwaso** [comment]
@operatorfilterer thank you! Would you mind releasing a new version that includes this change as an npm package?

**Pull request merged**
