### PR TITLE
Update README and OpenSea curated filter to remove Blur ExecutionDelegate

### PR DESCRIPTION
**Pull request by pacmanblur**
Blur now enforces royalties on NFTs that implement filtering https://twitter.com/blur_io/status/1592203711354261504?s=20&t=RQIV8F3LriskYIO_lpz-IA.

The README and on-chain filter list at `0x3cc6CddA760b79bAfa08dF41ECFA224f810dCeB6` should be updated so that creators can earn royalties on Blur.

### CODE REVIEW

**Comment by greenish** [comment]
Could we merge https://github.com/blur-io/operator-filter-registry by adding the blur subscription address to the readme here and creating `BlurDefaultOperatorFilterer.sol` and `OpenseaDefaultOperatorFilterer.sol`? 

Would be a huge win for the community / contributors to only have one version to maintain. ❤️

**Comment by 0xFlicker** [comment]
@greenish OpenSea has not removed Blur from the blocklist.

See https://twitter.com/opensea/status/1592377469956685827
image

`filteredOperators` for subscription 0x3cc6CddA760b79bAfa08dF41ECFA224f810dCeB6 still returns the blur delegate

image

**Comment by greenish** [comment]
I personally agree with OS here (even though they might do it for business reasons)
Why not support royalties for older collections? 
It's very clear what the intent of creators was. 
And going forward creators intent is being honored.
So why be inconsistent and only honor creators intent going forward when you are forced to?

**Comment by haowang1013** [comment]
It looks like blur has been removed from the filter list as of 6 days ago:
https://etherscan.io/tx/0xe8187869bd6efc095bb74f1f61356d85d308b1f1d2821998265d8da89b8120ef#eventlog

**Pull request closed without merging**
